// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xgpfgjseiogrghvbypqb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhncGZnanNlaW9ncmdodmJ5cHFiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njk5MjE0MjYsImV4cCI6MjA4NTQ5NzQyNn0.L-flZAFbKhNlCnvvM2ndneLT5uvwN30DwVZYdz1eHzw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});